### PR TITLE
Add hints and solutions for bkimminich/juice-shop#1409 (geo stalking challenges)

### PR DESCRIPTION
**Pull request by justinsmid**
Adds hints and solutions for bkimminich/juice-shop#1409

### CODE REVIEW

**Comment by bkimminich** [comment]
Thanks! Could you please take a look at https://github.com/bkimminich/juice-shop/issues/1347 and update the user emails? Also the step-by-step solution should not leave anything to "do" for the reader, so please add the full steps including the actual solution (e.g. mention the actual name of the forest) and make the last step just entering that name and submit. Please check the other solutions where it follows the same pattern. Thanks! 👍

**Comment by justinsmid** [comment]
@bkimminich We've updated the emails and solution steps. Please let me know if there is anything else that you would like us to change!

**Comment by bkimminich** [comment]
Looks good, we'll just have to fix the section headlines to match the expected ones on the Score Board, otherwise the links won't work:

* Determine the answer to John's security question
* Determine the answer to Emma's security question

Those need to be in both the hint and solution headline. And in the README the links need to be accordingly with `#determine-the-answer-to-johns-security-question` and `#determine-the-answer-to-emmas-security-question` suffix.

**Comment by bkimminich** [comment]
Open items addressed in https://github.com/bkimminich/pwning-juice-shop/commit/f2ae86201bf73d251c66a97f02787ea44e170eb6 and merged from that branch.

**Pull request merged**
