### PR TITLE
Add hint & solution for Forged Review

### PR DESCRIPTION
**Pull request by mzfr**
I have added the Hints & Solution for **Forged Review: Post a product review as another user or edit any user's existing review.**

### CODE REVIEW

**Comment by bkimminich** [comment]
Thank you! Will verify your solution steps and merge asap!

**Comment by bkimminich** [comment]
Hi @mzfr! Thanks for your PR and your patience with me reviewing it! The other solutions never assume that the user is familiar or using Burp or ZAP. Steps like "intercept this, then ..." do not work as a step by step guide for all audiences. Also, the intro and hints are almost identical copies of the _Forged Feedback_ hints and intro text - up to the point where a mistake snuck in that you could do anonymous reviews (which you cannot - at least not via the normal UI).

**Comment by mzfr** [comment]
@bkimminich 	 I've used Burp because I noticed few [1](https://github.com/bkimminich/pwning-juice-shop/blob/master/appendix/solutions.md#perform-an-unwanted-information-disclosure-by-accessing-data-cross-domain) [2](https://github.com/bkimminich/pwning-juice-shop/blob/master/appendix/solutions.md#forge-an-almost-properly-rsa-signed-jwt-token) solution used burp suite but if you think using burp is not the right way then I can use developers tool or any other tool that you prefer.

And yes intro is similar to `Forged feedback` because I thought they are almost similar task. 

About the `Anonymous review`, for some reason I can actually do an anonymous review using normal UI.

image

I didn't do any `hacky` thing to post an anonymous review. 

I did the following thing to post an anonymous review:
1) `npm start`
2) Go to `http://localhost:3000/#/`
3) Click on any product and then submit the review and it accepted.

That is the reason I use `When not logged in, the review will
be posted anonymously` in the `intro` section.

**Comment by bkimminich** [comment]
Aaah, I am obviously too entangled in `develop` branch where the facelifted UI is in use already. There anonymous reviews are not possible via normal UI usage.

The existing Burp-powered solutions should be ones where such a tool is needed. The "easy" challenges should make use of DevTools or Postman preferably. That's just to keep it consistent for the reader and not have them jump from tool A to B to C randomly.

**Comment by mzfr** [comment]
oh okay. Since the facelifted UI will be in use I guess I'll just update the `intro` section and will try to make it sound different then the `Forged feedback` one.

okay so I'll just stick with firefox's devtool for writing the solution. 
I'll update the PR ASAP.

**Comment by mzfr** [comment]
@bkimminich 	I have made the suggested changes. Please review the PR and let me know if there are any other changes required.

**Comment by bkimminich** [comment]
Thanks, looks good!

**Pull request merged**
